---
# file: roles/users/tasks/main.yml

- name: Make sure www-data group exists
  group: name="www-data" state=present

- name: Make sure www-data user exists
  user: name="www-data" group="www-data" system=yes

- name: Create users
  user: name={{ item.username }} group={{ item.primary_group }} groups={{ item.add_to_groups }} shell={{ item.shell }} state={{ item.state }}
  with_items: users

- name: Add user public keys
  authorized_key: "user={{ item.0.username }} key='{{ lookup('file', item.1) }}'"
  with_subelements:
    - users
    - keys
